#!/bin/bash
set -euo pipefail
# =====================================================
# Cron Examples — Print sample crontab entries
# Usage: ./cron_examples.sh
# =====================================================

echo "======================================"
echo "  Sample Crontab Entries for Edge AI"
echo "======================================"
echo ""
echo "# Run a health check every 5 minutes and save to a log file"
echo "*/5 * * * * /home/pi/scripts/health_report.sh >> /home/pi/logs/health.log 2>&1"
echo ""
echo "# Download latest model every night at 2:30 AM"
echo "30 2 * * * /home/pi/scripts/download_model.sh https://example.com/model.tflite abc123hash >> /home/pi/logs/model_update.log 2>&1"
echo ""
echo "# Run batch inference every day at 6:00 AM on last night's captured data"
echo "0 6 * * * /home/pi/scripts/run_batch_inference.sh >> /home/pi/logs/inference.log 2>&1"
echo ""
echo "# Clean up old log files every Sunday at 3:00 AM (keep logs from last 7 days)"
echo "0 3 * * 0 find /home/pi/logs -name \"*.log\" -mtime +7 -delete"
echo ""
echo "======================================"
echo "  Cron Expression Reference"
echo "======================================"
echo ""
echo "# ┌────────── minute (0-59)"
echo "# │ ┌──────── hour (0-23)"
echo "# │ │ ┌────── day of month (1-31)"
echo "# │ │ │ ┌──── month (1-12)"
echo "# │ │ │ │ ┌── day of week (0-7, 0 and 7 = Sunday)"
echo "# │ │ │ │ │"
echo "# * * * * *  command"
echo ""
echo "* * * * *        # every minute"
echo "0 * * * *        # at the start of every hour"
echo "0 2 * * *        # every day at 2:00 AM"
echo "0 2 * * 0        # every Sunday at 2:00 AM"
echo "0 2 1 * *        # on the 1st day of every month at 2:00 AM"
echo "*/5 * * * *      # every 5 minutes"
echo "0 9-17 * * 1-5   # every hour from 9am to 5pm, Monday to Friday"
echo ""
echo "======================================"
echo "  Output Redirection Reference"
echo "======================================"
echo ""
echo ">   Write output to file (overwrites existing)"
echo ">>  Append output to file (adds to the end)"
echo "2>&1  Also capture error messages (not just normal output)"
echo ""
echo "Commands:"
echo "  crontab -e    # edit your cron schedule"
echo "  crontab -l    # list all scheduled tasks"
echo "  crontab -r    # remove all scheduled tasks (use carefully!)"
